### ISSUE TITLE
Uncaught Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232

### ISSUE THREAD

**Issue by rbodhipaksha** [edjubuh/atom-terminal-tab#5]
[Enter steps to reproduce:]

1. Click on "Build PROS project"
2. Error pops up

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [terminal-tab-plus](https://github.com/edjubuh/atom-terminal-tab) package 0.5.11

### Stack Trace

Uncaught Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232

```
At C:\Users\ryanbodhipaksha\.pros-editor\packages\terminal-tab-plus\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25

Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at /packages/terminal-tab-plus/node_modules/node-pty-prebuilt/lib/windowsPtyAgent.js:25:24)
    at /packages/terminal-tab-plus/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:45:24)
    at spawn (/packages/terminal-tab-plus/node_modules/node-pty-prebuilt/lib/index.js:27:12)
    at TerminalSession.openPseudoterminal (/packages/terminal-tab-plus/lib/terminal-session.js:52:12)
    at /packages/terminal-tab-plus/lib/terminal-session.js:19:21)
    at /packages/terminal-tab-plus/lib/main.js:33:47
    at createTerminalTab (/packages/pros-atom3/lib/util/Services.js:26:31)
    at HTMLElement.didDispatch (/packages/pros-atom3/lib/commands.js:48:14)
    at CommandRegistry.handleCommandEvent (C:/Program Files/PROS/editor/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (C:/Program Files/PROS/editor/resources/app/src/command-registry.js:273:23)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
     -9:56.6.0 editor:newline (input.hidden-input)
     -9:55.6.0 core:save (input.hidden-input)
  2x -9:46.7.0 pros:build (input.hidden-input)
  2x -6:27.5.0 pros:upload (input.hidden-input)
  3x -5:20.9.0 pros:build (input.hidden-input)
     -4:23.8.0 command-palette:toggle (input.hidden-input)
     -4:22.5.0 settings-view:open (input.hidden-input)
  2x -3:08.9.0 pros:build (input.hidden-input)
     -2:59.2.0 pros:upload (input.hidden-input)
  2x -1:45.1.0 pros:build (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.25 
ide-cquery 0.13.6 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.0.3 
teletype 0.13.3 
terminal-tab-plus 0.5.11 
tool-bar 1.1.10 
tool-bar-main 0.0.11 
```

**Comment by MechyFoxVT** [comment]
I'm getting this error also. Any help would be appreciated!

**Comment by Jonny5j** [comment]
I am also getting this, any fix yet?

**Comment by mitchellaidant** [comment]
I had this issue. My way to fix it was to disable real-time scanning on my antivirus McAffe until I was done compiling.

**Comment by NightWolves-Kitsune** [comment]
i also got this issue when i tried to open the pros terminal and when i tried to build the project

**Comment by herbyderb01** [comment]
> I had this issue. My way to fix it was to disable real-time scanning on my antivirus McAffe until I was done compiling.

This worked for me! thx
