### ISSUE TITLE
Failed to activate the terminal-tab-plus package

### ISSUE THREAD

**Issue by Michael-Sjogren** [edjubuh/atom-terminal-tab#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 4.2.6
**OS**: "Manjaro Linux"
**Thrown From**: [terminal-tab-plus](https://github.com/edjubuh/atom-terminal-tab) package 0.5.11

### Stack Trace

Failed to activate the terminal-tab-plus package

```
At The module '/home/michaels/.atom/packages/terminal-tab-plus/node_modules/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/home/michaels/.atom/packages/terminal-tab-plus/node_modules/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-ide-terminal/node_modules/node-pty-prebuilt/lib/unixTerminal.js:22:11)
    at /packages/atom-ide-terminal/node_modules/node-pty-prebuilt/lib/unixTerminal.js:266:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-ide-terminal/node_modules/node-pty-prebuilt/lib/index.js:13:20)
    at /packages/atom-ide-terminal/node_modules/node-pty-prebuilt/lib/index.js:50:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/terminal-tab-plus/lib/terminal-session.js:3:52)
    at /packages/terminal-tab-plus/lib/terminal-session.js:13:37)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
```

### Commands

```
```

### Non-Core Packages

```
material 2.2.0 
platformio-ide-terminal 2.9.1 
terminal-tab-plus 0.5.11 
```

**Comment by xavierfoucrier** [comment]
@edjubuh I have the same issue... package should be updated.

**Comment by TriMoon** [comment]
This issue is a month old, time enough to update it...
That's why I'm replacing it with something else now.
Anyone have a good replacement (without other bloat) that also allows to set the terminal as a login shell?
